#!/bin/bash

# GitHub Pages Deployment Commands
# Replace YOUR_USERNAME with your actual GitHub username

echo "🚀 GitHub Pages Setup Commands"
echo "================================"
echo ""
echo "1. First, create repository on GitHub:"
echo "   https://github.com"
echo "   Repository name: personal-webpage"
echo "   Make it PUBLIC"
echo ""
echo "2. Then run these commands:"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/personal-webpage.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "3. Enable GitHub Pages in repository Settings > Pages"
echo ""
echo "4. Your live website will be at:"
echo "   https://YOUR_USERNAME.github.io/personal-webpage/"
echo ""
echo "Fragment Navigation URLs:"
echo "   https://YOUR_USERNAME.github.io/personal-webpage/#basic-info"
echo "   https://YOUR_USERNAME.github.io/personal-webpage/#biography"
echo "   https://YOUR_USERNAME.github.io/personal-webpage/#why-joined"
echo "   https://YOUR_USERNAME.github.io/personal-webpage/#goals"
echo ""
echo "✅ Your files are ready for deployment!"
